name: yolov5-sensevis
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - pip
  - pip :
      - thop >= 0.1.1
  - gitpython>=3.1.30
  - matplotlib>=3.3
  - numpy>=1.23.5
  - opencv
  - pillow>=10.3.0
  - psutil
  - pyyaml>=5.3.1
  - requests>=2.32.0
  - scipy>=1.4.1
  - thop>=0.1.1
  - pytorch>=1.8.0
  - torchvision>=0.9.0
  - tqdm>=4.64.0
  - ultralytics>=8.2.34
  - tifffile
  - pandas>=1.1.4
  - seaborn>=0.11.0
  - setuptools>=65.5.1
  - wheel>=0.38.0
  - jupyter